#!/bin/bash
cd programs/source/alphabet
convert largealphabet_az.png BMP3:largealphabet_az.bmp
convert largealphabet_buky.png BMP3:largealphabet_buky.bmp
convert largealphabet_vede.png BMP3:largealphabet_vedebas.bmp
convert largealphabet_glagoli.png BMP3:largealphabet_glagoli.bmp
convert largealphabet_dobro.png BMP3:largealphabet_dobro.bmp
convert largealphabet_jest.png BMP3:largealphabet_jest.bmp
convert largealphabet_zhivete.png BMP3:largealphabet_zhivete.bmp
convert largealphabet_dzelo.png BMP3:largealphabet_dzelo.bmp
convert largealphabet_zemlja.png BMP3:largealphabet_zemlja.bmp
convert largealphabet_i.png BMP3:largealphabet_i.bmp
convert largealphabet_ize.png BMP3:largealphabet_ize.bmp
convert largealphabet_derv.png BMP3:largealphabet_derv.bmp
convert largealphabet_kako.png BMP3:largealphabet_kako.bmp
convert largealphabet_ljudije.png BMP3:largealphabet_ljudije.bmp
convert largealphabet_myslite.png BMP3:largealphabet_myslite.bmp
convert largealphabet_nash.png BMP3:largealphabet_nash.bmp
convert largealphabet_on.png BMP3:largealphabet_on.bmp
convert largealphabet_pokoi.png BMP3:largealphabet_pokoi.bmp
convert largealphabet_rtsi.png BMP3:largealphabet_rtsi.bmp
convert largealphabet_slovo.png BMP3:largealphabet_slovo.bmp
convert largealphabet_tvrdo.png BMP3:largealphabet_tvrdo.bmp
convert largealphabet_uk.png BMP3:largealphabet_uk.bmp
convert largealphabet_frt.png BMP3:largealphabet_frt.bmp
convert largealphabet_xer.png BMP3:largealphabet_xer.bmp
convert largealphabet_ot.png BMP3:largealphabet_ot.bmp
convert largealphabet_shta.png BMP3:largealphabet_shta.bmp
convert largealphabet_tsi.png BMP3:largealphabet_tsi.bmp
convert largealphabet_chrv.png BMP3:largealphabet_chrv.bmp
convert largealphabet_sha.png BMP3:largealphabet_sha.bmp
convert largealphabet_jer_i.png BMP3:largealphabet_jer_i.bmp
convert largealphabet_jery.png BMP3:largealphabet_jery.bmp
convert largealphabet_jer_u.png BMP3:largealphabet_jer_u.bmp
convert largealphabet_jat.png BMP3:largealphabet_jat.bmp
convert largealphabet_ju.png BMP3:largealphabet_ju.bmp
convert largealphabet_ja.png BMP3:largealphabet_ja.bmp
convert largealphabet_je.png BMP3:largealphabet_je.bmp
convert largealphabet_nasal_e.png BMP3:largealphabet_nasal_e.bmp
convert largealphabet_nasal_o.png BMP3:largealphabet_nasal_o.bmp
convert largealphabet_nasal_je.png BMP3:largealphabet_nasal_je.bmp
convert largealphabet_nasal_jo.png BMP3:largealphabet_nasal_jo.bmp
convert largealphabet_ksi.png BMP3:largealphabet_ksi.bmp
convert largealphabet_psi.png BMP3:largealphabet_psi.bmp
convert largealphabet_fita.png BMP3:largealphabet_fita.bmp
convert largealphabet_izica.png BMP3:largealphabet_izica.bmp
convert largealphabet_uk_fragment.png BMP3:largealphabet_uk_fragment.bmp
convert smallalphabet_az.png BMP3:smallalphabet_az.bmp
convert smallalphabet_buky.png BMP3:smallalphabet_buky.bmp
convert smallalphabet_vede.png BMP3:smallalphabet_vede.bmp
convert smallalphabet_glagoli.png BMP3:smallalphabet_glagoli.bmp
convert smallalphabet_dobro.png BMP3:smallalphabet_dobro.bmp
convert smallalphabet_jest.png BMP3:smallalphabet_jest.bmp
convert smallalphabet_zhivete.png BMP3:smallalphabet_zhivete.bmp
convert smallalphabet_dzelo.png BMP3:smallalphabet_dzelo.bmp
convert smallalphabet_zemlja.png BMP3:smallalphabet_zemlja.bmp
convert smallalphabet_i.png BMP3:smallalphabet_i.bmp
convert smallalphabet_ize.png BMP3:smallalphabet_ize.bmp
convert smallalphabet_derv.png BMP3:smallalphabet_derv.bmp
convert smallalphabet_kako.png BMP3:smallalphabet_kako.bmp
convert smallalphabet_ljudije.png BMP3:smallalphabet_ljudije.bmp
convert smallalphabet_myslite.png BMP3:smallalphabet_myslite.bmp
convert smallalphabet_nash.png BMP3:smallalphabet_nash.bmp
convert smallalphabet_on.png BMP3:smallalphabet_on.bmp
convert smallalphabet_pokoi.png BMP3:smallalphabet_pokoi.bmp
convert smallalphabet_rtsi.png BMP3:smallalphabet_rtsi.bmp
convert smallalphabet_slovo.png BMP3:smallalphabet_slovo.bmp
convert smallalphabet_tvrdo.png BMP3:smallalphabet_tvrdo.bmp
convert smallalphabet_uk.png BMP3:smallalphabet_uk.bmp
convert smallalphabet_frt.png BMP3:smallalphabet_frt.bmp
convert smallalphabet_xer.png BMP3:smallalphabet_xer.bmp
convert smallalphabet_ot.png BMP3:smallalphabet_ot.bmp
convert smallalphabet_shta.png BMP3:smallalphabet_shta.bmp
convert smallalphabet_tsi.png BMP3:smallalphabet_tsi.bmp
convert smallalphabet_chrv.png BMP3:smallalphabet_chrv.bmp
convert smallalphabet_sha.png BMP3:smallalphabet_sha.bmp
convert smallalphabet_jer_i.png BMP3:smallalphabet_jer_i.bmp
convert smallalphabet_jery.png BMP3:smallalphabet_jery.bmp
convert smallalphabet_jer_u.png BMP3:smallalphabet_jer_u.bmp
convert smallalphabet_jat.png BMP3:smallalphabet_jat.bmp
convert smallalphabet_ju.png BMP3:smallalphabet_ju.bmp
convert smallalphabet_ja.png BMP3:smallalphabet_ja.bmp
convert smallalphabet_je.png BMP3:smallalphabet_je.bmp
convert smallalphabet_nasal_e.png BMP3:smallalphabet_nasal_e.bmp
convert smallalphabet_nasal_o.png BMP3:smallalphabet_nasal_o.bmp
convert smallalphabet_nasal_je.png BMP3:smallalphabet_nasal_je.bmp
convert smallalphabet_nasal_jo.png BMP3:smallalphabet_nasal_jo.bmp
convert smallalphabet_ksi.png BMP3:smallalphabet_ksi.bmp
convert smallalphabet_psi.png BMP3:smallalphabet_psi.bmp
convert smallalphabet_fita.png BMP3:smallalphabet_fita.bmp
convert smallalphabet_izica.png BMP3:smallalphabet_izica.bmp
convert smallalphabet_uk_fragment.png BMP3:smallalphabet_uk_fragment.bmp
